# Generated by Django 5.0.6 on 2024-07-10 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Client Say'),
            preserve_default=False,
        ),
    ]
